// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class AirBookSeat
{
    public int Id { get; set; }

    public int AirFlightSeatId { get; set; }

    public int TicketInvoicingDetailId { get; set; }

    public DateTime ReservationTime { get; set; }

    public int? TransferPaymentId { get; set; }

    public decimal? HandlingFee { get; set; }

    public string SeatAssignmentNum { get; set; }

    public virtual AirFlightSeat AirFlightSeat { get; set; }

    public virtual TicketInvoicingDetail TicketInvoicingDetail { get; set; }

    public virtual TransferPayment TransferPayment { get; set; }
}