// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class AirCabin
{
    public int Id { get; set; }

    public string CabinClass { get; set; }

    public virtual ICollection<AirCabinRule> AirCabinRules { get; set; } = new List<AirCabinRule>();

    public virtual ICollection<AirCabinSeat> AirCabinSeats { get; set; } = new List<AirCabinSeat>();

    public virtual ICollection<AirFlightSeat> AirFlightSeats { get; set; } = new List<AirFlightSeat>();

    public virtual ICollection<AirMeal> AirMeals { get; set; } = new List<AirMeal>();
}