// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class AirFlightManagement
{
    public int Id { get; set; }

    public string FlightCode { get; set; }

    public int DepartureAirportId { get; set; }

    public int ArrivalAirportId { get; set; }

    public string DepartureTerminal { get; set; }

    public string ArrivalTerminal { get; set; }

    public TimeOnly DepartureTime { get; set; }

    public TimeOnly ArrivalTime { get; set; }

    public string DayofWeek { get; set; }

    public int Mile { get; set; }

    public int CrossDay { get; set; }

    public virtual ICollection<AirFlight> AirFlights { get; set; } = new List<AirFlight>();

    public virtual ICollection<AriTicketPrice> AriTicketPrices { get; set; } = new List<AriTicketPrice>();

    public virtual AirPort ArrivalAirport { get; set; }

    public virtual AirPort DepartureAirport { get; set; }

    public virtual ICollection<Luggage> Luggage { get; set; } = new List<Luggage>();
}