// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class AirType
{
    public int Id { get; set; }

    public string FlightModel { get; set; }

    public int TotalSeat { get; set; }

    public int MaxMile { get; set; }

    public int MaxWeight { get; set; }

    public string ManufactureCompany { get; set; }

    public string Introduction { get; set; }

    public string Img { get; set; }

    public virtual ICollection<AirCabinSeat> AirCabinSeats { get; set; } = new List<AirCabinSeat>();

    public virtual ICollection<AirOwn> AirOwns { get; set; } = new List<AirOwn>();

    public virtual ICollection<SeatGroup> SeatGroups { get; set; } = new List<SeatGroup>();
}