// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class AriTicketPrice
{
    public int Id { get; set; }

    public int AirCabinRuleId { get; set; }

    public int AirFlightManagementId { get; set; }

    public decimal Price { get; set; }

    public virtual AirCabinRule AirCabinRule { get; set; }

    public virtual AirFlightManagement AirFlightManagement { get; set; }
}