// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class Campaign
{
    public int Id { get; set; }

    public string CampaignType { get; set; }

    public string Type { get; set; }

    public virtual ICollection<CampaignsCoupon> CampaignsCoupons { get; set; } = new List<CampaignsCoupon>();

    public virtual ICollection<CampaignsDiscount> CampaignsDiscounts { get; set; } = new List<CampaignsDiscount>();
}