// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class CampaignsDiscountTfitem
{
    public int Id { get; set; }

    public int CampaignsDiscountId { get; set; }

    public int TfitemId { get; set; }

    public virtual CampaignsDiscount CampaignsDiscount { get; set; }

    public virtual Tfitem Tfitem { get; set; }
}