// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class CampaignsFlightCouponsUsageHistory
{
    public int Id { get; set; }

    public int CampaignsCouponId { get; set; }

    public int TicketId { get; set; }

    public DateTime UsedDate { get; set; }

    public string Status { get; set; }

    public DateTime? DateCreated { get; set; }

    public int OriginalPrice { get; set; }

    public int DiscountAmount { get; set; }

    public int DiscountedPrice { get; set; }

    public virtual CampaignsCoupon CampaignsCoupon { get; set; }

    public virtual Ticket Ticket { get; set; }
}