// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class CampaignsCouponAirFlight
{
    public int Id { get; set; }

    public int CampaignsCouponId { get; set; }

    public int AirFlightId { get; set; }

    public virtual AirFlight AirFlight { get; set; }

    public virtual CampaignsCoupon CampaignsCoupon { get; set; }
}