// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class CampaignsCoupon
{
    public int Id { get; set; }

    public int CampaignId { get; set; }

    public string Name { get; set; }

    public DateTime DateStart { get; set; }

    public DateTime DateEnd { get; set; }

    public DateTime DateCreated { get; set; }

    public string Status { get; set; }

    public decimal DiscountValue { get; set; }

    public int DiscountQuantity { get; set; }

    public int AvailableQuantity { get; set; }

    public int? MinimumOrderValue { get; set; }

    public int MaximumDiscountAmount { get; set; }

    public string Code { get; set; }

    public bool DisplayDescription { get; set; }

    public string MemberCriteria { get; set; }

    public string AirFlightsCriteria { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual ICollection<CampaignsCouponAirFlight> CampaignsCouponAirFlights { get; set; } = new List<CampaignsCouponAirFlight>();

    public virtual ICollection<CampaignsCouponMember> CampaignsCouponMembers { get; set; } = new List<CampaignsCouponMember>();

    public virtual ICollection<CampaignsFlightCouponsUsageHistory> CampaignsFlightCouponsUsageHistories { get; set; } = new List<CampaignsFlightCouponsUsageHistory>();
}