// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class CompanyStaff
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int CompanyJobId { get; set; }

    public string Status { get; set; }

    public DateTime RegistrationTime { get; set; }

    public virtual ICollection<CampaignsDiscountStatusNotification> CampaignsDiscountStatusNotifications { get; set; } = new List<CampaignsDiscountStatusNotification>();

    public virtual CompanyJob CompanyJob { get; set; }

    public virtual ICollection<CompanyStaffLoginLog> CompanyStaffLoginLogs { get; set; } = new List<CompanyStaffLoginLog>();

    public virtual ICollection<CompanyStaffsChangePasswordLog> CompanyStaffsChangePasswordLogs { get; set; } = new List<CompanyStaffsChangePasswordLog>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<PermissionGroupsAddStaff> PermissionGroupsAddStaffs { get; set; } = new List<PermissionGroupsAddStaff>();
}