// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class CompanyDepartment
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? OrderBy { get; set; }

    public virtual ICollection<CompanyJob> CompanyJobs { get; set; } = new List<CompanyJob>();
}