// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class LuggageOrder
{
    public int Id { get; set; }

    public int TicketInvoicingDetailId { get; set; }

    public int LuggageId { get; set; }

    public int Amount { get; set; }

    public int Price { get; set; }

    public DateTime OrderTime { get; set; }

    public int TransferPaymentsId { get; set; }

    public string OrderStatus { get; set; }

    public string LuggageNum { get; set; }

    public virtual Luggage Luggage { get; set; }

    public virtual TicketInvoicingDetail TicketInvoicingDetail { get; set; }

    public virtual TransferPayment TransferPayments { get; set; }
}