// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class Message
{
    public int Id { get; set; }

    public int MessageBoxId { get; set; }

    public DateTime SendTime { get; set; }

    public string MessageContent { get; set; }

    public int? MemberId { get; set; }

    public int? CompanyStaffId { get; set; }

    public bool IsReaded { get; set; }

    public DateTime? ReadedTime { get; set; }

    public virtual CompanyStaff CompanyStaff { get; set; }

    public virtual Member Member { get; set; }

    public virtual MessageBox MessageBox { get; set; }
}