// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class MessageBox
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public bool IsProcessed { get; set; }

    public DateTime? ProcessedTime { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}