// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class PermissionGroupsAddStaff
{
    public int Id { get; set; }

    public int PermissionGroupsId { get; set; }

    public int CompanyStaffsId { get; set; }

    public virtual CompanyStaff CompanyStaffs { get; set; }

    public virtual PermissionGroup PermissionGroups { get; set; }
}