// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class PermissionGroup
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Ddescribe { get; set; }

    public string Criteria { get; set; }

    public virtual ICollection<PermissionGroupsAddStaff> PermissionGroupsAddStaffs { get; set; } = new List<PermissionGroupsAddStaff>();

    public virtual ICollection<PermissionSetting> PermissionSettings { get; set; } = new List<PermissionSetting>();
}