// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class Tfitem
{
    public int Id { get; set; }

    public int TfcategoriesId { get; set; }

    public string Name { get; set; }

    public string SerialNumber { get; set; }

    public string Image { get; set; }

    public int Quantity { get; set; }

    public int UnitPrice { get; set; }

    public string Description { get; set; }

    public bool IsPublished { get; set; }

    public virtual ICollection<CampaignsDiscountTfitem> CampaignsDiscountTfitems { get; set; } = new List<CampaignsDiscountTfitem>();

    public virtual Tfcategory Tfcategories { get; set; }

    public virtual ICollection<Tforderlist> Tforderlists { get; set; } = new List<Tforderlist>();

    public virtual ICollection<Tfreservelist> Tfreservelists { get; set; } = new List<Tfreservelist>();

    public virtual ICollection<Tfwishlist> Tfwishlists { get; set; } = new List<Tfwishlist>();
}