// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class Tforderlist
{
    public int Id { get; set; }

    public int TicketDetailsId { get; set; }

    public int TfitemsId { get; set; }

    public int Quantity { get; set; }

    public int UnitPrice { get; set; }

    public int? TforderStatusId { get; set; }

    public virtual Tfitem Tfitems { get; set; }

    public virtual TforderStatus TforderStatus { get; set; }

    public virtual TicketDetail TicketDetails { get; set; }
}