// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class Ticket
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int AirFlightId { get; set; }

    public string OrderNum { get; set; }

    public decimal TotalPayableAmount { get; set; }

    public decimal ActualPaidAmount { get; set; }

    public DateTime OrderTime { get; set; }

    public int TransferPaymentId { get; set; }

    public bool IsEstablished { get; set; }

    public int? MileRedemption { get; set; }

    public int TotalGeneratedMile { get; set; }

    public bool IsInvoiced { get; set; }

    public virtual AirFlight AirFlight { get; set; }

    public virtual ICollection<CampaignsFlightCouponsUsageHistory> CampaignsFlightCouponsUsageHistories { get; set; } = new List<CampaignsFlightCouponsUsageHistory>();

    public virtual Member Member { get; set; }

    public virtual ICollection<TicketCancel> TicketCancels { get; set; } = new List<TicketCancel>();

    public virtual ICollection<TicketDetail> TicketDetails { get; set; } = new List<TicketDetail>();

    public virtual TransferPayment TransferPayment { get; set; }
}