// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Infa.EFModel.Models;

public partial class TicketInvoicingDetail
{
    public int Id { get; set; }

    public int TicketDetailId { get; set; }

    public int AirFlightSeatId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public int CountryId { get; set; }

    public DateTime DateofBirth { get; set; }

    public bool Gender { get; set; }

    public string PassportNum { get; set; }

    public DateTime PassportExpirationDate { get; set; }

    public string Remark { get; set; }

    public string TicketNum { get; set; }

    public int AirMealId { get; set; }

    public bool CheckInStatus { get; set; }

    public DateTime? CheckInTime { get; set; }

    public virtual ICollection<AirBookSeat> AirBookSeats { get; set; } = new List<AirBookSeat>();

    public virtual AirFlightSeat AirFlightSeat { get; set; }

    public virtual AirMeal AirMeal { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<LuggageOrder> LuggageOrders { get; set; } = new List<LuggageOrder>();

    public virtual TicketDetail TicketDetail { get; set; }
}