// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class AirCabinRule
{
    public int Id { get; set; }

    public int AirCabinId { get; set; }

    public string CabinCode { get; set; }

    public int Priority { get; set; }

    public int ShipmentWeight { get; set; }

    public int ShipmentCount { get; set; }

    public int CarryBagCount { get; set; }

    public int CarryBagWeight { get; set; }

    public bool PreSelectedSeat { get; set; }

    public double AccumulatedMile { get; set; }

    public bool MileUpgrade { get; set; }

    public int TicketVaildity { get; set; }

    public int RefundFee { get; set; }

    public int NoShowFee { get; set; }

    public bool FreeWifi { get; set; }

    public virtual AirCabin AirCabin { get; set; }

    public virtual ICollection<AriTicketPrice> AriTicketPrices { get; set; } = new List<AriTicketPrice>();

    public virtual ICollection<TicketDetail> TicketDetails { get; set; } = new List<TicketDetail>();
}