// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class AirFlight
{
    public int Id { get; set; }

    public int AirOwnId { get; set; }

    public int AirFlightManagementId { get; set; }

    public DateTime ScheduledDeparture { get; set; }

    public DateTime ScheduledArrival { get; set; }

    public int AirFlightSaleStatusId { get; set; }

    public virtual AirFlightManagement AirFlightManagement { get; set; }

    public virtual AirFlightSaleStatus AirFlightSaleStatus { get; set; }

    public virtual ICollection<AirFlightSeat> AirFlightSeats { get; set; } = new List<AirFlightSeat>();

    public virtual AirOwn AirOwn { get; set; }

    public virtual ICollection<AirTakeOffStatus> AirTakeOffStatuses { get; set; } = new List<AirTakeOffStatus>();

    public virtual ICollection<CampaignsCouponAirFlight> CampaignsCouponAirFlights { get; set; } = new List<CampaignsCouponAirFlight>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}