// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class AirFlightStatus
{
    public int Id { get; set; }

    public string Status { get; set; }

    public virtual ICollection<AirTakeOffStatus> AirTakeOffStatuses { get; set; } = new List<AirTakeOffStatus>();
}