// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class AirMeal
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int AirCabinId { get; set; }

    public string MealContent { get; set; }

    public string Image { get; set; }

    public byte[] ImageBit { get; set; }

    public string Category { get; set; }

    public virtual AirCabin AirCabin { get; set; }

    public virtual ICollection<TicketInvoicingDetail> TicketInvoicingDetails { get; set; } = new List<TicketInvoicingDetail>();
}