// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class AirOwn
{
    public int Id { get; set; }

    public int AirTypeId { get; set; }

    public string RegistrationNum { get; set; }

    public string Status { get; set; }

    public int ManufactureYear { get; set; }

    public virtual ICollection<AirFlight> AirFlights { get; set; } = new List<AirFlight>();

    public virtual AirType AirType { get; set; }
}