// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class AirPort
{
    public int Id { get; set; }

    public string Lata { get; set; }

    public string Gps { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public string AirPortName { get; set; }

    public int TimeArea { get; set; }

    public int Zone { get; set; }

    public string CityIntroduction { get; set; }

    public string Img { get; set; }

    public string Continent { get; set; }

    public virtual ICollection<AirFlightManagement> AirFlightManagementArrivalAirports { get; set; } = new List<AirFlightManagement>();

    public virtual ICollection<AirFlightManagement> AirFlightManagementDepartureAirports { get; set; } = new List<AirFlightManagement>();
}