// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class CompanyStaffsChangePasswordLog
{
    public int Id { get; set; }

    public int CompanyStaffId { get; set; }

    public string Password { get; set; }

    public DateTime UpdateTime { get; set; }

    public virtual CompanyStaff CompanyStaff { get; set; }
}