// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class MemberClass
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int ClassOrder { get; set; }

    public int MileageStart { get; set; }

    public int MileageEnd { get; set; }

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();
}