// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class MileOrder
{
    public int Id { get; set; }

    public int Amount { get; set; }

    public int? Price { get; set; }

    public DateTime OrderTime { get; set; }

    public int TransferPaymentId { get; set; }

    public string OrderStatus { get; set; }

    public string MileNum { get; set; }

    public int MemberId { get; set; }

    public virtual Member Member { get; set; }

    public virtual TransferPayment TransferPayment { get; set; }
}