// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class MileApply
{
    public int Id { get; set; }

    public int Change { get; set; }

    public int EventId { get; set; }

    public int ChoseId { get; set; }

    public int? Final { get; set; }

    public virtual MileageDetail Chose { get; set; }

    public virtual MileageDetail Event { get; set; }
}