// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class SeatArea
{
    public int Id { get; set; }

    public string SeatGroup { get; set; }

    public virtual ICollection<SeatGroup> SeatGroups { get; set; } = new List<SeatGroup>();
}