// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class TforderStatus
{
    public int Id { get; set; }

    public DateTime? PaidTime { get; set; }

    public DateTime? FulfilledTime { get; set; }

    public DateTime? CancelledTime { get; set; }

    public DateTime? RefundTime { get; set; }

    public DateTime? StockedTime { get; set; }

    public bool? Paid { get; set; }

    public bool? Fulfilled { get; set; }

    public bool? Cancelled { get; set; }

    public bool? Refund { get; set; }

    public bool? Stocked { get; set; }

    public int? TfreserveId { get; set; }

    public virtual Tfreserf Tfreserve { get; set; }
}