// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class Tfreservelist
{
    public int Id { get; set; }

    public int TfreserveId { get; set; }

    public int TfitemsId { get; set; }

    public int Quantity { get; set; }

    public int UnitPrice { get; set; }

    public int? Discount { get; set; }

    public int TotalPrice { get; set; }

    public virtual ICollection<CampaignsTfdiscountUsageHistory> CampaignsTfdiscountUsageHistories { get; set; } = new List<CampaignsTfdiscountUsageHistory>();

    public virtual Tfitem Tfitems { get; set; }

    public virtual Tfreserf Tfreserve { get; set; }
}