// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class Tfreserf
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int TicketDetailsId { get; set; }

    public int? Discount { get; set; }

    public int TotalPrice { get; set; }

    public int TransferPaymentId { get; set; }

    public int? TforderStatusId { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<TforderStatus> TforderStatuses { get; set; } = new List<TforderStatus>();

    public virtual ICollection<Tfreservelist> Tfreservelists { get; set; } = new List<Tfreservelist>();

    public virtual TicketDetail TicketDetails { get; set; }

    public virtual TransferPayment TransferPayment { get; set; }
}