// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class TicketCancel
{
    public int Id { get; set; }

    public int TicketId { get; set; }

    public int TicketCancelStatusId { get; set; }

    public int TransferRefundId { get; set; }

    public decimal OriginalOrderAmount { get; set; }

    public decimal TotalHandlingFee { get; set; }

    public decimal ActualRefundAmount { get; set; }

    public DateTime ApplicationTime { get; set; }

    public string Remark { get; set; }

    public string RefundFeeDetail { get; set; }

    public DateTime? ProcessingTime { get; set; }

    public virtual Ticket Ticket { get; set; }

    public virtual TicketCancelStatus TicketCancelStatus { get; set; }

    public virtual TransferRefund TransferRefund { get; set; }
}