// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class TicketDetail
{
    public int Id { get; set; }

    public int TicketId { get; set; }

    public int AirCabinRuleId { get; set; }

    public int TypeofPassengerId { get; set; }

    public decimal TicketAmount { get; set; }

    public int AccruedMile { get; set; }

    public string BookRef { get; set; }

    public virtual AirCabinRule AirCabinRule { get; set; }

    public virtual ICollection<Tforderlist> Tforderlists { get; set; } = new List<Tforderlist>();

    public virtual ICollection<Tfreserf> Tfreserves { get; set; } = new List<Tfreserf>();

    public virtual Ticket Ticket { get; set; }

    public virtual ICollection<TicketInvoicingDetail> TicketInvoicingDetails { get; set; } = new List<TicketInvoicingDetail>();

    public virtual TypeofPassenger TypeofPassenger { get; set; }
}