// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class TransferPayment
{
    public int Id { get; set; }

    public int TransferMethodsId { get; set; }

    public DateTime PaymentDate { get; set; }

    public decimal PaymentAmount { get; set; }

    public string Info { get; set; }

    public virtual ICollection<AirBookSeat> AirBookSeats { get; set; } = new List<AirBookSeat>();

    public virtual ICollection<LuggageOrder> LuggageOrders { get; set; } = new List<LuggageOrder>();

    public virtual ICollection<MileOrder> MileOrders { get; set; } = new List<MileOrder>();

    public virtual ICollection<Tfreserf> Tfreserves { get; set; } = new List<Tfreserf>();

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();

    public virtual TransferMethod TransferMethods { get; set; }

    public virtual ICollection<TransferRefund> TransferRefunds { get; set; } = new List<TransferRefund>();
}