// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SparkleAir.Front.API.Models;

public partial class TransferMethod
{
    public int Id { get; set; }

    public string PaymentMethod { get; set; }

    public virtual ICollection<TransferPayment> TransferPayments { get; set; } = new List<TransferPayment>();

    public virtual ICollection<TransferRefund> TransferRefunds { get; set; } = new List<TransferRefund>();
}